#!/usr/bin/env bash
#install nginx web server

apt-get update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www
sudo chmod -R 755 /var/www
touch /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html
sudo service nginx restart
