#!/usr/bin/env bash
#debbuging docker errors 
#make an Apavhe server return a Hello Holberton 

sudo apt-get update -y
sudo apt-get install -y apache2
sudo /etc/init.d/apache2 start
echo "Hello Holberton" | sudo tee -a /var/www/html/index.htmlsudo /etc/init.d/apache2 restart
